### ISSUE TITLE
Missing declaration file?

### ISSUE THREAD

**Issue by nat-alia** [thecodealer/vue-panzoom#16]
Error on Visual Code saying:

Could not find a declaration file for module 'vue-panzoom'. '/Users/nataliaoledzka/Documents/Capstone/capstone-codemarch22/node_modules/vue-panzoom/dist/vue-panzoom.umd.js' implicitly has an 'any' type.
  Try `npm install @types/vue-panzoom` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-panzoom';`ts(7016)

Tried npm install @types/vue-panzoom and tried to add a new declaration file but either I did it incorrectly or it doesn't work.

Thank you!

**Comment by janvorisek** [comment]
Create a new file `src/vue-panzoom.d.ts` and put `declare module "vue-panzoom";` inside of it. You will stop getting the error (but no type hinting will be available).

**Comment by iwalucas** [comment]
@janvorisek I am having the same issue, and its not working even declaring the d.ts.... any other idea?

**Comment by janvorisek** [comment]
@iwalucas The author needs to publish the built library files into the npm releases. This also coulld be automated in the build process. I'll send PR when I can.
