### ISSUE TITLE
Update panzoom version to 9.4.0

### ISSUE THREAD

**Issue by alekbless** [thecodealer/vue-panzoom#24]
Any plans to upgrade panzoom to the next version? If wanted I can submit a pull-request for this.

**Comment by thecodealer** [comment]
Sure, please do

**Comment by thecodealer** [comment]
> Any plans to upgrade panzoom to the next version? If wanted I can submit a pull-request for this.

Sure, please do

**Comment by thecodealer** [comment]
closing this as the package has been updated to the latest version
